/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLK83as3umV-0OqkUijnG6_2GQPE-2RE',
    appId: '1:865611136536:web:a09828c3b312ebe5440d6d',
    messagingSenderId: '865611136536',
    projectId: 'loginscreen-46def',
    authDomain: 'loginscreen-46def.firebaseapp.com',
    storageBucket: 'loginscreen-46def.appspot.com',
    measurementId: 'G-VGM7S7DD8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zFJS8Tk__HGd47AQFW5SIVnLTcQRSK8',
    appId: '1:865611136536:android:7332264ab97e9b4b440d6d',
    messagingSenderId: '865611136536',
    projectId: 'loginscreen-46def',
    storageBucket: 'loginscreen-46def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYRGutuBOE-MOtcpeyThb3IdiuIOWsNE',
    appId: '1:865611136536:ios:17ce1f20ad1e953d440d6d',
    messagingSenderId: '865611136536',
    projectId: 'loginscreen-46def',
    storageBucket: 'loginscreen-46def.appspot.com',
    iosBundleId: 'com.example.loginModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJYRGutuBOE-MOtcpeyThb3IdiuIOWsNE',
    appId: '1:865611136536:ios:89f5d062b9607795440d6d',
    messagingSenderId: '865611136536',
    projectId: 'loginscreen-46def',
    storageBucket: 'loginscreen-46def.appspot.com',
    iosBundleId: 'com.example.loginModule.RunnerTests',
  );
}

*/